---
title: 'Simulation Results: Scenario 1'
author: "Ismaila Ba"
date: '2019-10-09'
output: pdf_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::read_chunk(here::here("R", "proj_fonctions.R"))
knitr::read_chunk(here::here("R", "proj_packages.R"))
knitr::read_chunk(here::here("R", "Scenario_Variables_Simules.R"))
load(here::here("data","ScenarioI.RData"))
```

```{r Standardize the covariates}
```

```{r required-packages}
```

```{r ScenarioI1}
```

```{r ScenarioI2}
```

```{r ScenarioI3}
```

```{r Selection Performance}
```

```{r Properties of the estimate}
```

\[
W_1 = [0,250] \times [0,125],\quad W_2 = [0,500] \times [0,250] \quad \mbox{and} \quad W_3 = [0,1000] \times [0,500]. 
\]

```{r}
W <- rep(c("W1","W2","W3"),each=3)
Model <- rep(c("Strauss","Strauss","Geyer"),3)
nbre.pts <- round(c(Strauss.02_W1$l15,Strauss.05_W1$l15,Geyer_W1$l15,Strauss.02_W2$l15,Strauss.05_W2$l15,Geyer_W2$l15,Strauss.02_W3$l15,Strauss.05_W3$l15,Geyer_W3$l15))
```


```{r}
SCEN1.BIC.LASSO <- rbind(Estimate.Properties(Strauss.02_W1$l1,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l1,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l1,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l1,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l1,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l1,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l1,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l1,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l1,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.BIC.LASSO <- cbind(W,Model,SCEN1.BIC.LASSO,nbre.pts)
knitr::kable(SCENARIO1.BIC.LASSO, caption="Lasso penalty and cBIC")
```

```{r}
SCEN1.ERIC.LASSO <- rbind(Estimate.Properties(Strauss.02_W1$l2,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l2,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l2,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l2,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l2,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l2,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l2,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l2,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l2,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.ERIC.LASSO <- cbind(W,Model,SCEN1.ERIC.LASSO,nbre.pts)
knitr::kable(SCENARIO1.ERIC.LASSO, caption="Lasso penalty and ERIC")
```

```{r}
SCEN1.BIC.RIDGE <- rbind(Estimate.Properties(Strauss.02_W1$l3,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l3,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l3,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l3,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l3,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l3,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l3,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l3,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l3,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.BIC.RIDGE <- cbind(W,Model,SCEN1.BIC.RIDGE,nbre.pts)
knitr::kable(SCENARIO1.BIC.RIDGE, caption="Ridge penalty and cBIC")
```

```{r}
SCEN1.ERIC.RIDGE <- rbind(Estimate.Properties(Strauss.02_W1$l4,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l4,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l4,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l4,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l4,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l4,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l4,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l4,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l4,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.ERIC.RIDGE <- cbind(W,Model,SCEN1.ERIC.RIDGE,nbre.pts)
knitr::kable(SCENARIO1.ERIC.RIDGE, caption="Ridge penalty and ERIC")
```

```{r}
SCEN1.BIC.ENET <- rbind(Estimate.Properties(Strauss.02_W1$l5,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l5,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l5,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l5,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l5,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l5,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l5,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l5,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l5,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.BIC.ENET <- cbind(W,Model,SCEN1.BIC.ENET,nbre.pts)
knitr::kable(SCENARIO1.BIC.ENET, caption="Elastic Net penalty and cBIC")
```

```{r}
SCEN1.ERIC.ENET <- rbind(Estimate.Properties(Strauss.02_W1$l6,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l6,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l6,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l6,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l6,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l6,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l6,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l6,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l6,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.ERIC.ENET <- cbind(W,Model,SCEN1.ERIC.ENET,nbre.pts)
knitr::kable(SCENARIO1.ERIC.ENET, caption="Elastic Net penalty and ERIC")
```

```{r}
SCEN1.BIC.ALASSO <- rbind(Estimate.Properties(Strauss.02_W1$l7,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l7,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l7,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l7,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l7,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l7,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l7,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l7,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l7,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.BIC.ALASSO <- cbind(W,Model,SCEN1.BIC.ALASSO,nbre.pts)
knitr::kable(SCENARIO1.BIC.ALASSO, caption="Adaptive Lasso penalty and cBIC")
```

```{r}
SCEN1.ERIC.ALASSO <- rbind(Estimate.Properties(Strauss.02_W1$l8,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l8,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l8,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l8,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l8,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l8,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l8,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l8,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l8,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.ERIC.ALASSO <- cbind(W,Model,SCEN1.ERIC.ALASSO,nbre.pts)
knitr::kable(SCENARIO1.ERIC.ALASSO, caption="Adaptive Lasso penalty and ERIC")
```

```{r}
SCEN1.BIC.AENET <- rbind(Estimate.Properties(Strauss.02_W1$l9,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l9,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l9,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l9,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l9,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l9,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l9,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l9,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l9,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.BIC.AENET <- cbind(W,Model,SCEN1.BIC.AENET,nbre.pts)
knitr::kable(SCENARIO1.BIC.AENET, caption="Adaptive Elastic Net penalty and cBIC")
```

```{r}
SCEN1.ERIC.AENET <- rbind(Estimate.Properties(Strauss.02_W1$l10,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l10,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l10,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l10,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l10,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l10,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l10,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l10,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l10,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.ERIC.AENET <- cbind(W,Model,SCEN1.ERIC.AENET,nbre.pts)
knitr::kable(SCENARIO1.ERIC.AENET, caption="Adaptive Elastic Net penalty and ERIC")
```

```{r}
SCEN1.BIC.SCAD <- rbind(Estimate.Properties(Strauss.02_W1$l11,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l11,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l11,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l11,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l11,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l11,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l11,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l11,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l11,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.BIC.SCAD <- cbind(W,Model,SCEN1.BIC.SCAD,nbre.pts)
knitr::kable(SCENARIO1.BIC.SCAD, caption="Scad penalty and cBIC")
```

```{r}
SCEN1.ERIC.SCAD <- rbind(Estimate.Properties(Strauss.02_W1$l12,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l12,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l12,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l12,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l12,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l12,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l12,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l12,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l12,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.ERIC.SCAD <- cbind(W,Model,SCEN1.ERIC.SCAD,nbre.pts)
knitr::kable(SCENARIO1.ERIC.SCAD, caption="Scad penalty and ERIC")
```

```{r}
SCEN1.BIC.MCP <- rbind(Estimate.Properties(Strauss.02_W1$l13,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l13,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l13,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l13,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l13,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l13,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l13,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l13,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l13,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.BIC.MCP <- cbind(W,Model,SCEN1.BIC.MCP,nbre.pts)
knitr::kable(SCENARIO1.BIC.MCP, caption="Mcp penalty and BIC")
```

```{r}
SCEN1.ERIC.MCP <- rbind(Estimate.Properties(Strauss.02_W1$l14,Theta.Init.StraussI1.02,method="pen"),Estimate.Properties(Strauss.05_W1$l14,Theta.Init.StraussI1.05,method="pen"),Estimate.Properties(Geyer_W1$l14,Theta.Init.GeyerI1,method="pen"),Estimate.Properties(Strauss.02_W2$l14,Theta.Init.StraussI2.02,method="pen"),Estimate.Properties(Strauss.05_W2$l14,Theta.Init.StraussI2.05,method="pen"),Estimate.Properties(Geyer_W2$l14,Theta.Init.GeyerI2,method="pen"),Estimate.Properties(Strauss.02_W3$l14,Theta.Init.StraussI3.02,method="pen"),Estimate.Properties(Strauss.05_W3$l14,Theta.Init.StraussI3.05,method="pen"),Estimate.Properties(Geyer_W3$l14,Theta.Init.GeyerI3,method="pen"))
SCENARIO1.ERIC.MCP <- cbind(W,Model,SCEN1.ERIC.MCP,nbre.pts)
knitr::kable(SCENARIO1.ERIC.MCP, caption="Mcp penalty and ERIC")
```